name: Run MMSDKConnector unit tests
on:
  push:
    paths:
      - 'Frameworks/MMSDKConnector/**'
jobs:
  test:
    runs-on: self-hosted
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - uses: actions/checkout@v1
      - name: Test
        run: fastlane runMMSDKConnectorUnitTests
      - name: Upload report result
        continue-on-error: true
        uses: actions/upload-artifact@v2
        with:
          name: MMSDKConnector test report
          path: Frameworks/MMSDKConnector/fastlane/test_output/*
      - name: Generate XCov report
        continue-on-error: true
        run: fastlane runXcovReportMMSDKConnector
      - name: Upload report result
        continue-on-error: true
        uses: actions/upload-artifact@v2
        with:
          name: MMSDKConnector xcov report
          path: Frameworks/MMSDKConnector/xcov_output/*
