name: Unit tests
on: [pull_request]
jobs:
  validate:
    runs-on: self-hosted
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - uses: actions/checkout@v1
      - name: Test
        run: fastlane test
